name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Upload Cypress Report
        if: always() # Certifique-se de que o relat칩rio ser치 salvo mesmo se os testes falharem
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report # Nome do artifact
          path: cypress/reports # Caminho onde o relat칩rio est치 salvo
          retention-days: 3 # Define que o artifact expira em 3 dias
